/**
 * Help article data for CashPilot help center.
 * Self-contained - no external CMS needed.
 */

export interface HelpArticle {
  slug: string;
  title: string;
  category: string;
  categoryLabel: string;
  content: string;
  relatedSlugs: string[];
}

export const HELP_CATEGORIES = [
  { id: "getting-started", label: "Getting Started", description: "Learn the basics of CashPilot" },
  { id: "quickbooks", label: "QuickBooks Integration", description: "Connect and sync with QuickBooks Online" },
  { id: "reminders", label: "Managing Reminders", description: "Set up and manage payment reminders" },
  { id: "billing", label: "Billing & Account", description: "Manage your subscription and account" },
] as const;

export const helpArticles: HelpArticle[] = [
  {
    slug: "connecting-quickbooks",
    title: "Connecting QuickBooks",
    category: "getting-started",
    categoryLabel: "Getting Started",
    content: [
      "## Connecting QuickBooks to CashPilot",
      "",
      "CashPilot integrates directly with QuickBooks Online to import your invoices.",
      "",
      "### How to Connect",
      "",
      "1. Navigate to **Settings**.",
      "2. Click **Connect QuickBooks**.",
      "3. Authorize on the Intuit page.",
      "4. Grant CashPilot permission.",
      "5. You will be redirected back with a success message.",
      "",
      "### After Connecting",
      "",
      "Click **Sync Now** to import your invoices and customers.",
      "",
      "### Troubleshooting",
      "",
      "- Use QuickBooks **Online** (not Desktop)",
      "- Have admin access",
      "- Allow pop-ups",
    ].join("\n"),
    relatedSlugs: ["understanding-dashboard", "troubleshooting-sync", "what-data-we-sync"],
  },
  {
    slug: "understanding-dashboard",
    title: "Understanding Your Dashboard",
    category: "getting-started",
    categoryLabel: "Getting Started",
    content: [
      "## Understanding Your Dashboard",
      "",
      "Real-time overview of your accounts receivable health.",
      "",
      "### Key Metrics",
      "",
      "- **Expected Next 30 Days**: Open invoices due soon.",
      "- **Overdue Total**: Invoices past due date.",
      "- **Collected This Month**: Payments received.",
      "- **Collection Effectiveness**: Invoices paid within terms.",
      "",
      "### DSO",
      "",
      "Average days from invoice to payment.",
      "",
      "### Invoices at Risk",
      "",
      "60+ days overdue without engagement.",
      "",
      "### Quick Actions",
      "",
      "Sync, send reminders, or view overdue invoices.",
    ].join("\n"),
    relatedSlugs: ["connecting-quickbooks", "setting-up-reminders", "creating-email-templates"],
  },
  {
    slug: "setting-up-reminders",
    title: "Setting Up Reminders",
    category: "getting-started",
    categoryLabel: "Getting Started",
    content: [
      "## Setting Up Reminders",
      "",
      "Automatically send payment reminders based on cadences.",
      "",
      "### Quick Start",
      "",
      "1. **Create a Template** in Templates.",
      "2. **Set Up a Cadence** with timing rules.",
      "3. **Enable Reminders** for automatic sending.",
      "",
      "### Manual Reminders",
      "",
      "Send from any invoice detail page.",
      "",
      "### Best Practices",
      "",
      "- Friendly reminder before due date",
      "- Follow up 7 days after",
      "- Escalate at 30 days",
      "- Phone follow-up past 60 days",
    ].join("\n"),
    relatedSlugs: ["creating-email-templates", "setting-up-cadences", "pausing-resuming-reminders"],
  },
  {
    slug: "troubleshooting-sync",
    title: "Troubleshooting Sync Issues",
    category: "quickbooks",
    categoryLabel: "QuickBooks Integration",
    content: [
      "## Troubleshooting Sync Issues",
      "",
      "Common issues and solutions.",
      "",
      "### Sync Fails",
      "",
      "Token may be expired. Disconnect and reconnect.",
      "",
      "### Missing Invoices",
      "",
      "- Only outstanding invoices are synced",
      "- Last 12 months by default",
      "",
      "### Rate Limiting",
      "",
      "Once per minute to comply with API limits.",
    ].join("\n"),
    relatedSlugs: ["connecting-quickbooks", "reconnecting-quickbooks", "what-data-we-sync"],
  },
  {
    slug: "reconnecting-quickbooks",
    title: "Reconnecting QuickBooks",
    category: "quickbooks",
    categoryLabel: "QuickBooks Integration",
    content: [
      "## Reconnecting QuickBooks",
      "",
      "### When to Reconnect",
      "",
      "- Access expired after 100 days",
      "- Disconnected status in Settings",
      "- Switching QuickBooks companies",
      "",
      "### Steps",
      "",
      "1. Go to **Settings**.",
      "2. Click **Disconnect**.",
      "3. Click **Connect QuickBooks**.",
      "4. Authorize and **Sync Now**.",
      "",
      "### Existing Data",
      "",
      "Previously synced data remains. Records are updated on reconnect.",
    ].join("\n"),
    relatedSlugs: ["connecting-quickbooks", "troubleshooting-sync", "what-data-we-sync"],
  },
  {
    slug: "what-data-we-sync",
    title: "What Data We Sync",
    category: "quickbooks",
    categoryLabel: "QuickBooks Integration",
    content: [
      "## What Data We Sync",
      "",
      "### Customers",
      "",
      "- Name, email, phone",
      "",
      "### Invoices",
      "",
      "- Number, dates, amounts, status",
      "",
      "### NOT Synced",
      "",
      "- Line items, estimates, vendor data, taxes",
      "",
      "### Security",
      "",
      "- Encrypted in transit and at rest",
      "- Read-only access",
      "- Export or delete anytime",
    ].join("\n"),
    relatedSlugs: ["connecting-quickbooks", "troubleshooting-sync", "reconnecting-quickbooks"],
  },
  {
    slug: "creating-email-templates",
    title: "Creating Email Templates",
    category: "reminders",
    categoryLabel: "Managing Reminders",
    content: [
      "## Creating Email Templates",
      "",
      "Reusable reminder messages with dynamic variables.",
      "",
      "### Creating a Template",
      "",
      "1. Go to **Templates**.",
      "2. Click **New Template**.",
      "3. Enter name, subject, and body.",
      "4. Use variables like customer_name, balance, due_date.",
      "5. Click **Save**.",
      "",
      "### Available Variables",
      "",
      "customer_name, invoice_number, amount, balance, due_date, days_overdue, company_name",
      "",
      "### Best Practices",
      "",
      "- Clear subject lines",
      "- Professional tone",
      "- Templates for each overdue stage",
    ].join("\n"),
    relatedSlugs: ["setting-up-cadences", "setting-up-reminders", "pausing-resuming-reminders"],
  },
  {
    slug: "setting-up-cadences",
    title: "Setting Up Cadences",
    category: "reminders",
    categoryLabel: "Managing Reminders",
    content: [
      "## Setting Up Cadences",
      "",
      "Define automated reminder schedules.",
      "",
      "### What is a Cadence?",
      "",
      "A sequence of steps, each with a template and timing.",
      "",
      "### Creating a Cadence",
      "",
      "1. Go to **Templates**.",
      "2. Scroll to **Cadences**.",
      "3. Click **New Cadence**.",
      "4. Add steps with template and days.",
      "5. Negative numbers = before due date.",
      "",
      "### Default Cadence",
      "",
      "Mark one as default for all new invoices.",
    ].join("\n"),
    relatedSlugs: ["creating-email-templates", "setting-up-reminders", "pausing-resuming-reminders"],
  },
  {
    slug: "pausing-resuming-reminders",
    title: "Pausing & Resuming Reminders",
    category: "reminders",
    categoryLabel: "Managing Reminders",
    content: [
      "## Pausing & Resuming Reminders",
      "",
      "Temporarily stop reminders for specific invoices.",
      "",
      "### Pausing",
      "",
      "1. Open invoice detail page.",
      "2. Click **Pause Reminders**.",
      "",
      "### Resuming",
      "",
      "1. Open invoice detail page.",
      "2. Click **Resume Reminders**.",
      "",
      "### Bulk Pause",
      "",
      "Select multiple invoices in Pipeline for bulk pause/resume.",
    ].join("\n"),
    relatedSlugs: ["setting-up-reminders", "creating-email-templates", "setting-up-cadences"],
  },
  {
    slug: "managing-subscription",
    title: "Managing Your Subscription",
    category: "billing",
    categoryLabel: "Billing & Account",
    content: [
      "## Managing Your Subscription",
      "",
      "### Plans",
      "",
      "- **Free Trial**: 14-day full access",
      "- **Starter**: Up to 100 invoices",
      "- **Professional**: Unlimited",
      "",
      "### Subscribing",
      "",
      "1. Go to **Settings**.",
      "2. Click **Upgrade**.",
      "3. Complete Stripe checkout.",
      "",
      "### Cancellation",
      "",
      "Cancel anytime from Stripe portal. Access continues until period end.",
    ].join("\n"),
    relatedSlugs: ["understanding-usage-limits"],
  },
  {
    slug: "understanding-usage-limits",
    title: "Understanding Usage Limits",
    category: "billing",
    categoryLabel: "Billing & Account",
    content: [
      "## Understanding Usage Limits",
      "",
      "### Free Trial: 50 invoices, 20 reminders/month",
      "### Starter: 100 invoices, 50 reminders/month",
      "### Professional: Unlimited",
      "",
      "### Hitting a Limit",
      "",
      "- Invoice limit: Synced but reminders pause",
      "- Reminder limit: Auto-reminders pause for the month",
      "",
      "### Upgrading",
      "",
      "Upgrade anytime. Price difference is prorated.",
    ].join("\n"),
    relatedSlugs: ["managing-subscription"],
  },
];

export function getArticlesByCategory(category: string): HelpArticle[] {
  return helpArticles.filter((a) => a.category === category);
}

export function getArticleBySlug(slug: string): HelpArticle | undefined {
  return helpArticles.find((a) => a.slug === slug);
}

export function getRelatedArticles(article: HelpArticle): HelpArticle[] {
  return article.relatedSlugs
    .map((slug) => helpArticles.find((a) => a.slug === slug))
    .filter(Boolean) as HelpArticle[];
}

export function searchArticles(query: string): HelpArticle[] {
  const lower = query.toLowerCase();
  return helpArticles.filter(
    (a) =>
      a.title.toLowerCase().includes(lower) ||
      a.content.toLowerCase().includes(lower)
  );
}
